Repository CarryVan/Real_Time_Virtual_Home_Trainer, pull requests merged in 2021-12, with the labels that each got.

#1 add docker-compose & update Readme, docker image
  Dockerfile
  README.md
  docker-compose.yml
Labels: enhancement

#3 Ci/CD
  .github/workflows/build.yml
  deploy_ssh.sh
  pose_module.py
Labels: feature

#4 deploy test
  .dockerignore
  .github/workflows/build.yml
  Dockerfile
  README.md
  dataset/example/legraise.JPG
  dataset/example/lunge.JPG
  dataset/example/plank.JPG
  dataset/example/pushup.JPG
  dataset/example/squat.JPG
  deploy_ssh.sh
  docker-compose.yml
  font/GodoM.ttf
  model/lunge_model/body_language_lr.pkl
  pose_module.py
  server.py
  static/client.js
  templates/schedule.html
  templates/start.html
Labels: deployment

#5 duplicate master hot fix
  .github/workflows/build.yml
  deploy_ssh.sh
Labels: hotfix

#2 Model change
  VideoTransformTrack.py
  model/legraise_model/body_language_lr.pkl
  model/legraise_model/body_language_mlp.pkl
  model/lunge_model/body_language_lr.pkl
  model/lunge_model/body_language_mlp.pkl
  model/plank_model/body_language_lr.pkl
  model/plank_model/body_language_mlp.pkl
  model/pushup_model/body_language_lr.pkl
  model/pushup_model/body_language_mlp.pkl
  model/squat_model/body_language_lr.pkl
  model/squat_model/body_language_mlp.pkl
  pose_module.py
  server.py
Labels: enhancement

#7 modify dockerfile cmd
  Dockerfile
Labels: enhancement

#8 depoly 1218
  Dockerfile
  VideoTransformTrack.py
  model/legraise_model/body_language_lr.pkl
  model/legraise_model/body_language_mlp.pkl
  model/lunge_model/body_language_lr.pkl
  model/lunge_model/body_language_mlp.pkl
  model/plank_model/body_language_lr.pkl
  model/plank_model/body_language_mlp.pkl
  model/pushup_model/body_language_lr.pkl
  model/pushup_model/body_language_mlp.pkl
  model/squat_model/body_language_lr.pkl
  model/squat_model/body_language_mlp.pkl
  pose_module.py
  server.py
Labels: deployment

#13 hotfix requirements
  requirements.txt
  server.py
Labels: hotfix

#19 fix readme
  README.md
Labels: documentation
